Repository tymefighter/R5O5, pull requests merged in 2020-08, with the labels that each got.

#21 Kernelvec doc
  kernel/kernelvec.S
Labels: documentation

#13 Paging Helper Functions
  Makefile
  kernel/buffer.c
  kernel/declarations.h
  kernel/functions.h
  kernel/paging.c
Labels: important

#22 ReadBytes and WriteBytes with virtual mapping support
  kernel/buffer.c
  kernel/functions.h
Labels: enhancement

#25 Update read and write bytes functions to takes uint64 instead of int
  kernel/buffer.c
  kernel/functions.h
Labels: enhancement

#24 Initial implementation of program loader
  Makefile
  kernel/createProcess.c
  kernel/functions.h
Labels: important

#28 Create Process
  Makefile
  kernel/algo.c
  kernel/createProcess.c
  kernel/declarations.h
  kernel/elfReader.c
  kernel/functions.h
  kernel/interruptHandler.c
Labels: important

#29 added round robin scheduler and dispatcher
  Makefile
  kernel/functions.h
  kernel/interruptHandler.c
  kernel/main.c
  kernel/process.c
Labels: important

#30 Mkfs
  mkfs/r5o5_mkfs.c
Labels: enhancement, important

#33 Minor Bug Fix
  kernel/paging.c
Labels: bug

#34 Fix Paging
  kernel/paging.c
Labels: bug

#35 Fix Types
  kernel/declarations.h
  kernel/globalData.c
Labels: bug, important

#37 Set up GDB
  .gdbinit.tmpl-riscv
Labels: important
