Repository tymefighter/R5O5, pull requests merged in 2020-07, with the labels that each got.

#16 Structure Cleanup
  kernel/declarations.h
  kernel/globalData.c
Labels: cleanup

#11 Elf reader
  Makefile
  kernel/declarations.h
  kernel/elfReader.c
  kernel/functions.h
  kernel/globalData.c
Labels: important

#18 Fix Declarations
  kernel/declarations.h
Labels: bug
